name: smartnote
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.2.0
  animations: ^2.0.7
  avatar_glow: ^2.0.2
  bottom_navy_bar: ^6.0.0
  change_app_package_name: ^1.1.0
  chips_choice: ^3.0.0
  clipboard: ^0.1.3
  cloud_firestore: ^4.8.4
  file_picker: ^5.3.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  firebase_ui_auth: ^1.6.2
  firebase_ui_localizations: ^1.5.0
  firebase_ui_oauth: ^1.4.7
  firebase_ui_oauth_google: ^1.2.7
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_quill: ^7.3.2
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.2
  google_fonts: ^5.1.0
  hawk_fab_menu: ^1.2.0
  image_picker: ^1.0.2
  logger: null
  share_plus: ^7.1.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
