// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWlAgPH2N12jJUmk4Bx9KJfhb4c1rG9QQ',
    appId: '1:549178272813:web:347ee66443feb5e96d1ca4',
    messagingSenderId: '549178272813',
    projectId: 'smartnotes-b5ddc',
    authDomain: 'smartnotes-b5ddc.firebaseapp.com',
    storageBucket: 'smartnotes-b5ddc.appspot.com',
    measurementId: 'G-KE2X7JKD39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVKCcec405a5o4-cJLn33vppMXUw1pXUc',
    appId: '1:549178272813:android:afb76c82088ece6f6d1ca4',
    messagingSenderId: '549178272813',
    projectId: 'smartnotes-b5ddc',
    storageBucket: 'smartnotes-b5ddc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiid9tcMxk-ibYPgj1w1JIiuL1L0HHsgM',
    appId: '1:549178272813:ios:f591d9a4cbb8d3506d1ca4',
    messagingSenderId: '549178272813',
    projectId: 'smartnotes-b5ddc',
    storageBucket: 'smartnotes-b5ddc.appspot.com',
    iosClientId:
        '549178272813-6d6758j6c7kfh5vfjqhd6f5sml2htscp.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartnote',
  );
}
